#! /usr/local/bin/gmake
#  $Id: Makefile,v 1.4 2006-07-05 14:01:12 ninio Exp $

Libsources= 
#LIBNAME = 

EXEC = sametree shortenTree makeSureAllBranchesAreLargerThanEpsilon

include ../Makefile.generic
