#! /usr/local/bin/gmake
#  $Id: Makefile,v 1.1 2006-06-22 15:42:11 ninio Exp $

Libsources= checkCovClass.cpp
LIBNAME = checkCov


EXEC = checkCov

#checkCov: checkCovMain.o

include ../Makefile.generic
