#! /usr/local/bin/gmake
#  $Id: Makefile,v 1.2 2006-07-19 15:22:21 eyalprivman Exp $

Libsources= bblEM2codon.cpp bestAlphaAndK.cpp computeCounts2Codon.cpp empirSelectionModel.cpp fromCountTableComponentToDistance2Codon.cpp JTTcodonModel.cpp kaks4Site.cpp kaksOptions.cpp likeDist2Codon.cpp likelihoodComputation2Codon.cpp optimizeFanctors.cpp params.cpp siteSpecificForce.cpp statisticalScore.cpp utils.cpp wYangModel.cpp

LIBNAME = kaks

# LibCsources= cmdline.c
# LibCsources += getopt.c getopt1.c 

EXEC = kaks

include ../Makefile.generic
