#! /usr/local/bin/gmake
#  $Id: Makefile,v 1.4 2006-06-22 14:51:16 ninio Exp $

#Libsources= rate4site.cpp rate4siteOptions.cpp
Libsources= 

# LibCsources= cmdline.c
# LibCsources += getopt.c getopt1.c 

EXEC = rate4site

rate4site: main.o rate4siteOptions.o
rate4site.debug: main.debug.o rate4siteOptions.debug.o



include ../Makefile.generic
