#! /usr/local/bin/gmake
#  $Id: Makefile,v 2.37 2006-09-20 08:45:17 ninio Exp $

Libsources= approxSemphyDistance.cpp constantSemphyDistance.cpp	\
  correctToCanonialForm.cpp minSpanTree.cpp Multinomial.cpp	\
  rearangeTree.cpp semphy.cpp semphyDistance.cpp		\
  semphySearchBestTree.cpp semphyStep.cpp constraints.cpp	\
  bootstrapProvider.cpp mainSemphy.cpp distanceBasedSeqs2TreeFactory.cpp

LIBNAME = SEMPHY

# LibCsources= cmdline.c
# LibCsources += getopt.c getopt1.c 

EXEC = semphy


include ../Makefile.generic

