#! /usr/local/bin/gmake
#  $RCSfile: Makefile,v $ $Revision: 1.3 $ $Date: 2006-06-22 14:51:16 $

Libsources= 

# LibCsources= cmdline.c
# LibCsources += getopt.c getopt1.c 

EXEC = randGamma

include ../Makefile.generic

