#! /usr/local/bin/gmake
#  $Id: Makefile,v 1.5 2006-06-22 14:51:16 ninio Exp $

Libsources= 

# LibCsources= cmdline.c
# LibCsources += getopt.c getopt1.c 

EXEC = distanceEstimation

include ../Makefile.generic
