#! /usr/local/bin/gmake
#  $Id: Makefile,v 1.6 2006-06-22 11:27:30 ninio Exp $

Libsources= 

# LibCsources= cmdline.c
# LibCsources += getopt.c getopt1.c 

EXEC = distanceBasedSeqs2TreeSA

include ../Makefile.generic
